Flink files for streamingFileSink
lyft/flink pull request #25
Opened 2019-05-02 00:20 UTC by kailashhd

Allow the class to be public instead of private.

2019-05-02 17:35 UTC, yxu-valleytider approved these changes
LGTM.  Need to ping #compute to fast-forward the process.

2019-05-02 17:35 UTC, yxu-valleytider commented on flink-formats/flink-parquet/pom.xml
> +		<version>1.8-lyft20190407</version>
nit: the date may need to be updated

2019-05-02 21:23 UTC, tweise commented on flink-formats/flink-parquet/pom.xml
> +		<version>1.8-lyft20190407</version>
Why this change?

2019-05-02 21:27 UTC, tweise requested changes
Please first get agreement for the upstream change and prepare a pull request. Then this PR needs to be tagged with the JIRA. We need to continue to follow this process to ensure that we are not introducing incompatible changes into the fork that will later make upgrades difficult. The process as such isn't new, please check with @glaksh100 if you have questions.

2019-05-03 17:04 UTC, yxu-valleytider commented
There's a solution now which does not require changing Flink upstream.

2019-05-03 18:14 UTC, kailashhd commented
@tweise: This is a WIP branch. Not planning on merging this. You can ignore this 
PR for the time being. Will come back to this along with going on the correct process to upstream this change.

2019-07-27 02:27 UTC, closed without merging